import os
import json
import shutil
from pathlib import Path

class ProjectInitializer:
    """
    项目初始化模块，用于在指定workspace目录下创建全新的项目根目录，建立标准化项目结构
    """
    
    def __init__(self, workspace_dir, project_name):
        """
        初始化项目初始化器
        
        Args:
            workspace_dir: 工作空间目录
            project_name: 项目名称
        """
        self.workspace_dir = Path(workspace_dir)
        self.project_name = project_name
        self.project_dir = self.workspace_dir / project_name
        
    def initialize(self):
        """
        初始化项目，创建标准化项目结构
        
        Returns:
            bool: 初始化是否成功
        """
        try:
            # 创建项目根目录
            self.project_dir.mkdir(parents=True, exist_ok=True)
            
            # 创建标准化项目结构
            self._create_project_structure()
            
            # 生成项目配置文件
            self._generate_project_config()
            
            # 初始化版本控制
            self._initialize_version_control()
            
            return True
        except Exception as e:
            print(f"项目初始化失败: {e}")
            return False
    
    def _create_project_structure(self):
        """
        创建标准化项目结构
        """
        # 创建基本目录结构
        directories = [
            'src',
            'tests',
            'docs',
            'config',
            'scripts',
            'assets'
        ]
        
        for directory in directories:
            (self.project_dir / directory).mkdir(exist_ok=True)
        
        # 创建src目录下的子目录
        src_subdirs = [
            'core',
            'utils',
            'api',
            'ui'
        ]
        
        for subdir in src_subdirs:
            (self.project_dir / 'src' / subdir).mkdir(exist_ok=True)
        
        # 创建基本文件
        self._create_initial_files()
    
    def _create_initial_files(self):
        """
        创建初始文件
        """
        # 创建README.md
        readme_content = f"# {self.project_name}\n\nProject generated by gocode.\n"
        with open(self.project_dir / 'README.md', 'w', encoding='utf-8') as f:
            f.write(readme_content)
        
        # 创建requirements.txt
        requirements_content = "# Dependencies\n"
        with open(self.project_dir / 'requirements.txt', 'w', encoding='utf-8') as f:
            f.write(requirements_content)
        
        # 创建main.py
        main_content = """def main():
    print('Hello, World!')

if __name__ == '__main__':
    main()
"""
        with open(self.project_dir / 'src' / 'main.py', 'w', encoding='utf-8') as f:
            f.write(main_content)
    
    def _generate_project_config(self):
        """
        生成项目配置文件
        """
        config = {
            'project_name': self.project_name,
            'version': '0.1.0',
            'description': f'{self.project_name} project',
            'author': '',
            'dependencies': [],
            'settings': {
                'python_version': '3.8+'
            }
        }
        
        with open(self.project_dir / 'config' / 'project_config.json', 'w', encoding='utf-8') as f:
            json.dump(config, f, indent=2, ensure_ascii=False)
    
    def _initialize_version_control(self):
        """
        初始化版本控制
        """
        # 创建.gitignore文件
        gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class

# Environment
.env
.venv/
venv/
env/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# Build
build/
dist/
*.egg-info/

# Test
.coverage
coverage.xml
pytest_cache/
"""
        with open(self.project_dir / '.gitignore', 'w', encoding='utf-8') as f:
            f.write(gitignore_content)
        
        # 尝试初始化git仓库
        try:
            import subprocess
            subprocess.run(['git', 'init'], cwd=str(self.project_dir), capture_output=True, check=True)
            subprocess.run(['git', 'add', '.'], cwd=str(self.project_dir), capture_output=True, check=True)
            subprocess.run(['git', 'commit', '-m', 'Initial commit'], cwd=str(self.project_dir), capture_output=True, check=True)
        except Exception as e:
            print(f"初始化git仓库失败: {e}")
            # 继续执行，git不是必须的
